import { Game, GameElement } from '../../interfaces'

const secretHitlerElements: GameElement[] = [
    { imgSrc: 'secretHitler/liberalBoard.png', id: 'liberalBoard', width: 20, height: 6, position: [12, -2, -4] },
    { imgSrc: 'secretHitler/fascistPolicy.png', id: 'fascistPolicy1' },
    { imgSrc: 'secretHitler/liberalPolicy.png', id: 'liberalPolicy1' },
    { imgSrc: 'secretHitler/president.png', id: 'president', width: 10, height: 3 },
    { imgSrc: 'secretHitler/chancellor.png', id: 'chancellor', width: 10, height: 3 },
    { imgSrc: 'secretHitler/hitlerSecretRole.png', id: 'hitlerSecretRole' },
    { imgSrc: 'secretHitler/fascistSecretRole.png', id: 'fascistSecretRole1' },
    { imgSrc: 'secretHitler/fascistSecretRole.png', id: 'fascistSecretRole2' },
    { imgSrc: 'secretHitler/fascistSecretRole.png', id: 'fascistSecretRole3' },
    { imgSrc: 'secretHitler/liberalSecretRole.png', id: 'liberalSecretRole1' },
    { imgSrc: 'secretHitler/liberalSecretRole.png', id: 'liberalSecretRole2' },
    { imgSrc: 'secretHitler/liberalSecretRole.png', id: 'liberalSecretRole3' },
    { imgSrc: 'secretHitler/liberalSecretRole.png', id: 'liberalSecretRole4' },
    { imgSrc: 'secretHitler/liberalSecretRole.png', id: 'liberalSecretRole5' },
    { imgSrc: 'secretHitler/liberalSecretRole.png', id: 'liberalSecretRole6' },
    { imgSrc: 'secretHitler/fascistPM.png', id: 'fascistPM1' },
    { imgSrc: 'secretHitler/fascistPM.png', id: 'fascistPM2' },
    { imgSrc: 'secretHitler/fascistPM.png', id: 'fascistPM3' },
    { imgSrc: 'secretHitler/fascistPM.png', id: 'fascistPM4' },
    { imgSrc: 'secretHitler/liberalPM.png', id: 'liberalPM1' },
    { imgSrc: 'secretHitler/liberalPM.png', id: 'liberalPM2' },
    { imgSrc: 'secretHitler/liberalPM.png', id: 'liberalPM3' },
    { imgSrc: 'secretHitler/liberalPM.png', id: 'liberalPM4' },
    { imgSrc: 'secretHitler/liberalPM.png', id: 'liberalPM5' },
    { imgSrc: 'secretHitler/liberalPM.png', id: 'liberalPM6' },
    { imgSrc: 'secretHitler/fascistPolicy.png', id: 'fascistPolicy2' },
    { imgSrc: 'secretHitler/fascistPolicy.png', id: 'fascistPolicy3' },
    { imgSrc: 'secretHitler/fascistPolicy.png', id: 'fascistPolicy4' },
    { imgSrc: 'secretHitler/fascistPolicy.png', id: 'fascistPolicy5' },
    { imgSrc: 'secretHitler/fascistPolicy.png', id: 'fascistPolicy6' },
    { imgSrc: 'secretHitler/fascistPolicy.png', id: 'fascistPolicy7' },
    { imgSrc: 'secretHitler/fascistPolicy.png', id: 'fascistPolicy8' },
    { imgSrc: 'secretHitler/fascistPolicy.png', id: 'fascistPolicy9' },
    { imgSrc: 'secretHitler/fascistPolicy.png', id: 'fascistPolicy10' },
    { imgSrc: 'secretHitler/fascistPolicy.png', id: 'fascistPolicy11' },
    { imgSrc: 'secretHitler/liberalPolicy.png', id: 'liberalPolicy2' },
    { imgSrc: 'secretHitler/liberalPolicy.png', id: 'liberalPolicy3' },
    { imgSrc: 'secretHitler/liberalPolicy.png', id: 'liberalPolicy4' },
    { imgSrc: 'secretHitler/liberalPolicy.png', id: 'liberalPolicy5' },
    { imgSrc: 'secretHitler/liberalPolicy.png', id: 'liberalPolicy6' },
    { imgSrc: 'secretHitler/yaBallot.png', id: 'yaBallot1' },
    { imgSrc: 'secretHitler/yaBallot.png', id: 'yaBallot2' },
    { imgSrc: 'secretHitler/yaBallot.png', id: 'yaBallot3' },
    { imgSrc: 'secretHitler/yaBallot.png', id: 'yaBallot4' },
    { imgSrc: 'secretHitler/yaBallot.png', id: 'yaBallot5' },
    { imgSrc: 'secretHitler/yaBallot.png', id: 'yaBallot6' },
    { imgSrc: 'secretHitler/yaBallot.png', id: 'yaBallot7' },
    { imgSrc: 'secretHitler/yaBallot.png', id: 'yaBallot8' },
    { imgSrc: 'secretHitler/yaBallot.png', id: 'yaBallot9' },
    { imgSrc: 'secretHitler/yaBallot.png', id: 'yaBallot10' },
    { imgSrc: 'secretHitler/neinBallot.png', id: 'neinBallot1' },
    { imgSrc: 'secretHitler/neinBallot.png', id: 'neinBallot2' },
    { imgSrc: 'secretHitler/neinBallot.png', id: 'neinBallot3' },
    { imgSrc: 'secretHitler/neinBallot.png', id: 'neinBallot4' },
    { imgSrc: 'secretHitler/neinBallot.png', id: 'neinBallot5' },
    { imgSrc: 'secretHitler/neinBallot.png', id: 'neinBallot6' },
    { imgSrc: 'secretHitler/neinBallot.png', id: 'neinBallot7' },
    { imgSrc: 'secretHitler/neinBallot.png', id: 'neinBallot8' },
    { imgSrc: 'secretHitler/neinBallot.png', id: 'neinBallot9' },
    { imgSrc: 'secretHitler/neinBallot.png', id: 'neinBallot10' },
]

const secretHitler: Game = {
    name: 'Secret Hitler',
    elements: secretHitlerElements
}

export default secretHitler